# Generated by Django 3.0.dev20190625091245 on 2019-06-27 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last modified'),
        ),
    ]
